### ISSUE TITLE
Cache and retry username/pw tokens

### ISSUE THREAD

**Issue by perryqh** [G5/g5_authentication_client#26]
Service to service API calls generate tons of tokens. It'd be nice to cache tokens and automatically regenerate them on 401s.

I'm not really satisfied with this solution and am hoping for feedback, but consumers could do something like:
```
response = G5AuthenticationClient::Client.new.do_with_username_pw_access_token do |token|
  HTTParty.get(CxmClient.api_person_url(client_urn, id), query_options(token))
end
```
and G5AuthenticationClient::Client could implement this functionality:
```
  # Return response to 'yield'
    # Yield response should have a 'code' method for the http status code
    def do_with_username_pw_access_token
      response = yield username_pw_access_token
      if 401 == response.code.to_i
        @@username_pw_access_token = nil
        response                  = yield username_pw_access_token
      end
      response
    end

    def username_pw_access_token
      raise 'allow_password_credentials must be enabled for username/pw access' unless allow_password_credentials?

      @@username_pw_access_token ||= oauth_client.password.get_token(username, password)
    end
```

**Comment by perryqh** [comment]
If we forced everyone to use httpparty then 
```
 response_code = response.response.code.to_i
if 401 == response_code
```
could go to the auth client

**Comment by dpetersen** [comment]
This seems totally reasonable to me. The only other thing I could think to do, and I'm not even sure if it's a good idea, is the gem could provide it's own `#get`/`#post`/etc on the client that would automatically retry for you. You'd probably still want this more basic retry functionality for people who want to use their own HTTP libraries.

Then again, your HTTP library *must* return a response object that has a `code` function that returns a `t_i`-able object, so we can't be *that* flexible. I guess people could write their own adapters that check the class of the response object and make it work...
